### ISSUE TITLE
Add event + attribute to all elements that are connected/hydrated

### ISSUE THREAD

**Issue by eddyloewen** [webtides/element-js#151]
## Problem
When client side rendering custom elements, there's currently no standard way to identify whether an element has been connected/hydrated. Especially when looking for nested elements from a top/parent element. This creates challenges for managing the "flash of unstyled content" and can produce massive layout shifts during the hydration process.

## Proposed Solution
Implement a connected/hydrated indicator system in element-js that would:
1. Add a specific attribute (e.g., `connected="true"` or `hydrated="true"`) to elements once they're connected and hydrated
2. Dispatch a custom event (e.g., `connected`) when the hydration process is complete
3. Consider supporting CSS custom states as an alternative to attributes

## Discussion Points
- Should we use a custom attribute or leverage CSS custom states (`:--connected`)?
- What should the attribute/state be named? (`hydrated`, `connected`, `ready`, etc.)
- Should we dispatch an event?
- Are there performance implications to consider?

## Benefits
- Enables proper "cloaking" mechanisms for unhydrated (nested) elements

## Example CSS to cloak a (deeply) nested element
```css
parent-element:defined:has(deeply-nested-element:not([connected='true'])) {
  height: 500px;
  opacity: 0;

  @media (min-width: 768px) {
    height: 1000px;
  }
}
```
